spring:
  application:
    name: replication
  sql:
    init:
      mode: never

server:
  port: 8080

app:
  datasource:
    writer:
      url: jdbc:postgresql://localhost:5432/appdb
      username: app
      password: app123
      driver-class-name: org.postgresql.Driver

    reader:
      url: jdbc:postgresql://localhost:5433/appdb
      username: app
      password: app123
      driver-class-name: org.postgresql.Driver


