CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'replica123';
CREATE TABLE IF NOT EXISTS items (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


INSERT INTO items (name) VALUES ('item inicial');
